### ISSUE TITLE
DB modifications

### ISSUE THREAD

**Issue by mariuscrsn** [WattRex/Battery-Cycler-Drivers#33]
- [x] Add deprecated field on cycler station table: https://github.com/WattRex/Battery-Cycler-Drivers/blob/3da2321ac8bd471b4773bc00cd8d5da35e01365b/code/drv_db/src/wattrex_driver_db/drv_db_dao.py#L158
- [x] Update redoxElectrolyte table to insert min flow rate, intial SOC and polarity

**Comment by RobertoAldea** [comment]
- [x] Added database for link configuration for devices, missing in driver master

**Comment by RobertoAldea** [comment]
- [x] LinkConfiguration Database has Property column as primary key

**Comment by RobertoAldea** [comment]
- [x] MASTER DB Instructions modes has to be CC_MODE CP_MODE CV_MODE

**Comment by mariuscrsn** [comment]
- [x] On table `ComputationalUnit`, `HostName`, `IP` and `Port` must not be unique.
- [x] Add `MAC` field to `ComputationalUnit` table

**Comment by javibu13** [comment]
> * [x]  Add deprecated field on cycler station table: https://github.com/WattRex/Battery-Cycler-Drivers/blob/3da2321ac8bd471b4773bc00cd8d5da35e01365b/code/drv_db/src/wattrex_driver_db/drv_db_dao.py#L158
> * [ ]  Update redoxElectrolyte table to insert min flow rate, intial SOC and polarity

Fixed in drv_db_dao_master.py in future commits.

**Comment by javibu13** [comment]
> * [x]  On table `ComputationalUnit`, `HostName`, `IP` and `Port` must not be unique.
> * [ ]  Add `MAC` field to `ComputationalUnit` table

Fixed with last CU configuration (CUID, HostName, IP, Port, User, LastConnection, Available)
