### ISSUE TITLE
Warning in db master clases

### ISSUE THREAD

**Issue by RobertoAldea** [WattRex/Battery-Cycler-Drivers#74]
Warning in master clases inherinted from cache clases.
Now the code works but we keep getting this warning:
![image](https://github.com/WattRex/Battery-Cycler-Drivers/assets/103926227/0f2132c4-4c37-4af6-a3aa-065cdd873f0c)

This is what sqlalchemy says about it:

https://docs.sqlalchemy.org/en/20/faq/ormconfiguration.html#:~:text=As%20of%20SQLAlchemy%20version%200.9.5%2C%20the%20above%20condition%20is%20detected%2C%20and%20will%20warn%20that%20the%20id%20column%20of%20A%20and%20B%20is%20being%20combined%20under%20the%20same%2Dnamed%20attribute%20id%2C%20which%20above%20is%20a%20serious%20issue%20since%20it%20means%20that%20a%20B%20object%E2%80%99s%20primary%20key%20will%20always%20mirror%20that%20of%20its%20A.

**Comment by mariuscrsn** [comment]
Solved on pull request
